# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

melissa = User.create(name: "Melissa Funk", username: "melissafunk")
gabe = User.create(name: "Gabe Rodriguez", username: "gaberodgriguez")

carbonara = Recipe.create(title: "Carbonara", image: "https://assets.bonappetit.com/photos/5a6f48f94f860a026c60fd71/16:9/w_960,c_limit/pasta-carbonara.jpg", cuisine: "Italian", directions: "1. Heat 6 qt. water in a large pot over high. When water starts to steam, add 3 Tbsp. salt and cover pot with a lid (this will bring water to a boil faster; 2. While you are waiting on the water, do a little prep. Remove 4 oz. guanciale from packaging and cut into about 1x¼ strips. Finely grate 2 oz. cheese and set aside one-quarter of cheese for later; 3. Whisk 4 egg yolks and 2 whole eggs in a medium bowl until no streaks remain, then stir in remaining grated cheese. Add several cranks of pepper and set aside; 4. Working next to pot, heat 2 Tbsp. oil in a large Dutch oven or other heavy pot over medium. Add guanciale and cook, stirring occasionally, until crisp around the edges, 7–10 minutes; 5. Remove pot from heat. Using a wooden spoon, fish out guanciale and transfer to a small bowl. Pour fat into a heatproof measuring cup, then add back about 3 Tbsp. to pot. Discard any remaining fat; 6. Cook 1 lb. pasta in boiling water, stirring occasionally, 2 minutes shy of package instructions. Just before pasta is finished, scoop out 1¾ cups pasta cooking liquid with same heatproof measuring cup; 7. Add 1 cup reserved pasta cooking liquid to Dutch oven and bring to a boil over medium-high. Drain pasta in a colander, then transfer to Dutch oven; 8. Cook pasta, stirring constantly and vigorously, until al dente and water is reduced by about half, about 2 minutes. Remove pot from heat; 9.Whisk ¼ cup pasta cooking liquid into reserved egg mixture, then very slowly stream into Dutch oven, stirring constantly, until cheese is melted and egg is thickened to form a glossy sauce. Season with salt, if needed. Thin sauce with remaining ½ cup pasta cooking liquid, adding a tablespoonful at a time, until it's the consistency of heavy cream (you most likely won’t use all of it); 10. Mix in guanciale and divide pasta among bowls. Top with pepper and reserved cheese.", ingredients: "4 servings; 3 Tbsp. kosher salt plus more; 4 oz. pancetta; 2 oz. parmesan; 4 large egg yolks; 2 large eggs, 2 Tbsp. extra-virgin olive oil; 1 lb. spaghetti, bucatini, or rigatoni; freshly ground black pepper")
meatballs = Recipe.create(title: "Meatballs", image: "https://www.cookerru.com/wp-content/uploads/2021/01/italian-meatballs-feature-2-web-1170x1463.jpg", cuisine: "Italian", directions: "1. Preheat the oven to 400°F (200°C) and line a baking sheet with parchment paper or a baking mat; 2. In a large mixing bowl, add Italian bread crumbs and milk. Combine well and set aside while preparing the other ingredients, for at least 5 minutes; 3. Add ground beef, onion, garlic, egg, salt, black pepper, parmesan cheese, and parsley into the soaked bread crumb mixture, and mix with your hands until just combined. Do not overmix; 4. Portion onto the prepared baking sheet (using a cookie or ice cream scoop will make it easier). Wet your hands with water, and roll meatballs into 2inch diameter balls; 5. Bake for about 15-20 minutes, or until the meatballs have reached an internal temperature of 165˚F (74°C). Remove from oven and drain off any excess fat. Serve with your favorite sauce and enjoy!", ingredients: "4 servings; 1/2 cup Italian bread crumbs; 2/3 cup milk; 1 lb ground beef; 1/4 medium onion finely diced or grated; 2 cloves garlic minced; 1 large egg; 1/4 cup parmesan cheese; 1 tbsp fresh parsley; 1 tsp salt; 1/2 tsp ground black pepper")
tonkatsu = Recipe.create(title: "Tonkatsu", image: "https://v1.nitrocdn.com/KQYMGOLIdXGmoAcyJsPOrQDKktgCbwtG/assets/static/optimized/rev-580dbe6/wp-content/uploads/2021/08/Tonkatsu-0030-II.jpg", cuisine: "Japanese", directions: "1. Make small cuts all over pork chops with tip of knife. Sprinkle salt and pepper on both sides of meat; 2. Coat the meat with flour, dip in eggs, then cover with bread crumbs; 3. Heat deep frying oil to 350 F, and deep fry crumb-covered meat. You can check the temperature by dropping a bread crumb. If it comes up to the oil surface right after it's dropped, it's good; 4. Fry until color turns golden brown and meat floats in the oil, about 5-8 minutes, turning once or twice; 5. Set the meat on a cooling rack for a minute. Cut into 5-6 pieces", ingredients: "4 servings; 4 pork loin chops (about 1-inch thick, no bones); 1/2 cup all purpose flour; 1-2 eggs; 1 cup panko or bread crumbs; oil for deep frying; salt; pepper")
oyakodon = Recipe.create(title: "Oyakodon", image: "https://www.justonecookbook.com/wp-content/uploads/2011/02/Oyakodon-w600-500x375.jpg", cuisine: "Japanese", directions: "1. Cook rice according to directions; 2. Place the chicken in a nonstick skillet with a lid, and cook and stir over medium heat until the chicken is no longer pink inside and beginning to brown, about 5 minutes. Stir in the onion, and cook and stir until the onion is soft, about 5 more minutes. Pour in the stock, and whisk in soy sauce, mirin, and brown sugar, stirring to dissolve the sugar. Bring the mixture to a boil, and let simmer until slightly reduced, about 10 minutes; 3. Whisk the eggs in a bowl until well-beaten, and pour over the chicken and stock. Cover the skillet, reduce heat, and allow to steam for about 5 minutes, until the egg is cooked. Remove from heat; 4. To serve, place 1 cup of cooked rice per bowl into 4 deep soup bowls, top each bowl with 1/4 of the chicken and egg mixture, and spoon about 1/2 cup of soup into each bowl", ingredients: "4 servings; 2 cups uncooked white rice; 4 cups water; 4 skinless, boneless chicken thighs, cut into small pieces; 1 onion, cut in half and sliced; 2 cups dashi stock, made with dashi powder; 1/4 cup soy sauce; 3 Tbsp mirin (Japanese rice wine); 3 Tbsp brown sugar; 4 eggs")
padthai = Recipe.create(title: "Pad Thai", image: "https://img.delicious.com.au/FTUW3Xvs/w759-h506-cfill/del/2017/07/chicken-and-prawn-pad-thai-49048-2.jpg", cuisine: "Thai", directions: "1. Cook noodles according to packet instructions. Drain and rinse under cold water. Set aside; 2. For the pad Thai sauce, heat oil in a wok over medium-low heat. Add the garlic and chilli, and cook, stirring, for 1 minute or until fragrant. Add the sugar, tamarind, fish sauce, soy sauce and 2 tbs water, and cook, stirring, until sugar dissolves. Bring to a simmer and cook for 2-3 minutes or until reduced slightly. Transfer to a small heatproof bowl and set aside; 3. Wipe wok clean and add oil. Add chicken and cook, stirring occasionally, for 5-6 minutes or until golden and cooked through. Push chicken to one side of wok and add prawn to empty side. Cook, turning halfway, for 2-3 minutes or until pink and just cooked through. Push prawn to one side with chicken and add egg to empty side. Cook, stirring, for 2 minutes or until just set; 4. Add bean sprouts, garlic chives, cooked noodles and pad Thai sauce, and cook, tossing together, for 2-3 minutes or until heated through; 5. Divide between bowls and serve immediately, sprinkled with roasted peanuts and with lime wedges on side", ingredients: "2 servings; 125g dried rice stick noodles, broken in half; 1 Tbsp sunflower oil; 200g chicken thigh fillets, cut into 2cm pieces; 8 large green prawns, peeled, deveined; 1 egg, lightly beaten; 100g bean sprouts; 1/2 bunch chives, cut into 3cm pieces; chopped roasted peanuts and lime wedges, to serve; For Sauce:; 2 tsp sunflower oil; 2 garlic cloved, crushed; 2 small red chillies, thinly sliced; 1 Tbsp finely grated brown sugar; 2 1/2 Tbsp taramind puree; 1 Tbsp fish sauce; 1 tsp light soy sauce")
larb = Recipe.create(title: "Pork Larb Salad", image: "https://img.delicious.com.au/DU_VU3jA/del/2015/10/thai-pork-larb-salad-14461-1.jpg", cuisine: "Thai", directions: "1. Heat the oil in a large frypan over medium-high heat; 2. Add the mince and cook, breaking up lumps with a wooden spoon, for 6-7 minutes until cooked through; 3. Use a slotted spoon to transfer the pork to a large bowl. Set aside to cool; 4. Place 1 tbs uncooked rice in a separate dry frypan and cook, stirring, over medium heat for 7-8 minutes or until dark golden. Transfer to a mortar and pestle and grind into a fine powder. Set rice powder aside until ready to serve; 5. To make the dressing, whisk together fish sauce and lime juice. Set aside until ready to serve; 6. Just before serving, add the dressing, eschalot, mint, basil and chilli to the pork and stir to combine; 7. Arrange the lettuce leaves on serving plates. Use a slotted spoon to pile the pork larb on top. Garnish with extra mint, basil and chilli. Sprinkle with rice powder and serve with steamed rice", ingredients: "4 servings; 1 Tbsp peanut oil; 500g pork mince; 1 Tbsp long-grain rice, plus steamed rice to serve; 2 Tbsp fish sauce; juice of 2 limes; 1 large eschalot, finely sliced; 1/2 bunch mint, leaves picked, plus extra to serve; 1/2 bunch Thai basil, leaves picked, plus extra to serve; 2 long red chillies, seeds removed, chopped, plus extra sliced to serve; 1 iceburg lettuce, leaves separated")
enchilada = Recipe.create(title: "Enchiladas Verdes", image: "https://mavencookery.com/wp-content/uploads/enchiladas-verdes-top-sq.jpeg", cuisine: "Mexican", directions: "1. In a saucepan, combine chicken breast with chicken broth, one quarter onion, a clove of garlic, and 2 teaspoons salt. Bring to a boil, and then boil for 20 minutes. Reserve broth, set chicken aside to cool, and discard onion and garlic. When cool enough to handle, shred chicken with your hands; 2. Place tomatillos and serrano chiles in a pot with water, enough to cover them. Bring to boil, and continue boiling until tomatillos turn a different shade of green (from bright green to a dull, army green). Strain tomatillos and chiles, and place in a blender with another quarter piece of onion, 1 clove garlic, and a pinch of salt. Pour in reserved chicken broth, so that liquid just covers the veggies in the blender by about an inch. Blend all ingredients until they are completely pureed. Pour salsa in a medium saucepan, and bring to a low boil; 3. Pour oil in a frying pan, and allow to get very hot. Slightly fry tortillas one by one in hot oil, setting each on a paper towel afterwards to soak some of the oil. Finally, dip slightly fried tortillas in low-boiling green salsa, until tortillas become soft again. Place on plates, 3 per person; 4. Fill or top tortillas with shredded chicken, then extra green sauce. Top with crumbled cheese, chopped onion, and chopped cilantro", ingredients: "4 servings; 2 bone-in chicken breast halves; 2 cups chicken broth; 1/4 white onion; 1 clove garlic; 2 tsp salt; 1 lb fresh tomatillos, husks removed; 5 serrano peppers; 1/4 white onion; 1 clove garlic; 1 pinch salt; 12 corn tortillas; 1/4 cup vegetable oil; 1 cup crumbled queso fresco; 1/2 white onion, chopped; 1 bunch fresh cilantro, chopped")
street_tacos = Recipe.create(title: "Carne Asada Street Tacos", image: "https://s23209.pcdn.co/wp-content/uploads/2019/04/Mexican-Street-TacosIMG_9091.jpg", cuisine: "Mexican", directions: "1. In a medium bowl, combine soy sauce, lime juice, 1 tablespoon canola oil, garlic, chili powder, cumin and oregano; 2. In a gallon size Ziploc bag or large bowl, combine soy sauce mixture and steak; marinate for at least 1 hour up to 4 hours, turning the bag occasionally; 3. Heat remaining 1 tablespoon canola oil in a large skillet over medium high heat. Add steak and marinade, and cook, stirring often, until steak has browned and marinade has reduced, about 5-6 minutes, or until desired doneness; 4. Serve steak in tortillas, topped with onion, cilantro and lime", ingredients: "6 servings; 2 Tbsp reduced sodium soy sauce; 2 Tbsp freshly squeezed lime juice; 2 Tbsp canola oil, divided; 3 cloves garlic, minced; 2 tsp chili powder; 1 tsp ground cumin; 1 tsp dried oregano; 1 1/2 lbs skirt steak, cut into 1/2 inch pieces; 12 corn tortillas, warmed; 3/4 cup diced onion; 1/2 cup chopped cilantro; 1 lime, cut into wedges")
ribeye = Recipe.create(title: "Ribeye Steak", image: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https://static.onecms.io/wp-content/uploads/sites/9/2014/01/10/201402-xl-butter-basted-rib-eye-steak-2000.jpg", cuisine: "American", directions: "1. Season the rib eye steaks all over with salt and freshly ground pepper. Let the meat stand at room temperature for 30 minutes; 2. In a large cast-iron skillet, heat the canola oil until shimmering. Add the steaks and cook over high heat until crusty on the bottom, about 5 minutes. Turn the steaks and add the butter, thyme, garlic and rosemary to the skillet. Cook over high heat, basting the steaks with the melted butter, garlic and herbs, until the steaks are medium-rare, 5 to 7 minutes longer. Transfer the steaks to a cutting board and let rest for 10 minutes. Cut the steaks off the bone, then slice the meat across the grain and serve.", ingredients: "Two 1 1/4-pound, bone-in rib eye steaks; Kosher Salt; Freshly ground pepper; 2 tablespoons canola oil; 4 tablespoons unsalted butter; 4 thyme sprigs; 3 garlic cloves; 1 rosemary sprig")
tritip = Recipe.create(title: "Tri-Tip with Chimichurri", image: "https://assets.epicurious.com/photos/577d24a8fdf2b77e68400f4f/master/w_1280%2Cc_limit/tri-tip-with-chimichuri-BA-070616.jpg", cuisine: "American", directions: "1. Mix sesame seeds, paprika, 2 Tbsp. oil, 2 tsp. salt, and 2 tsp. pepper in a small bowl to combine. Rub all over steak and let sit at room temperature 30 minutes; 2. Meanwhile, prepare a grill for medium-high, indirect heat (for a charcoal grill, bank coals on one side of grill; for a gas grill, leave one or two burners off). Place steak over indirect heat, cover grill, and grill, turning once, until an instant-read thermometer inserted into the thickest part of steak registers 115°F, 20–30 minutes. Move steak to direct heat and grill until lightly charred, about 2 minutes per side, or until an instant-read thermometer registers 120°F for medium-rare (temperature will continue to rise off heat). Transfer to a cutting board and let rest 10 minutes before slicing against the grain; 3. While steak is resting, combine garlic, parsley, cilantro, vinegar, agave nectar, and remaining 1/2 cup oil; season with salt and pepper Serve steak with chimichurri", ingredients: "1 tablespoon sesame seeds; 1 tablespoon smoked paprika; 2 tablespoons plus 1/2 cup olive oil; 2 teaspoons kosher salt, plus more; 2 teaspoons freshly ground black pepper; 2 pounds tri-tip steak or two 1-pound sirloin steaks; 2 garlic cloves,finely grated; 2 cups finely chopped parsley; 1/2 cup finely chopped cilantro; 1/4 cup red wine vinegar; 1 tablespoon agave nectar")

review1 = Review.create(rating: 3, favorite: false, used_id: 1, recipe_id: 1)
review2 = Review.create(rating: 4, favorite: true, used_id: 1, recipe_id: 3)
review3 = Review.create(rating: 5, favorite: true, used_id: 1, recipe_id: 5)
review4 = Review.create(rating: 3, favorite: false, used_id: 2, recipe_id: 2)
review5 = Review.create(rating: 4, favorite: true, used_id: 2, recipe_id: 4)
review6 = Review.create(rating: 5, favorite: true, used_id: 2, recipe_id: 10)
review7 = Review.create(rating: 4, favorite: true, used_id: 2, recipe_id: 8)

comment1 = Comment.create(comment: "This pad thai is so easy to make and really delicious!", user_id: 1, recipe_id: 5)
comment2 = Comment.create(comment: "This recipe is really simple, but the outcome is really yummy.", user_id: 2, recipe_id: 4)
comment3 = Comment.create(comment: "My tonkatsu came out so crispy!", user_id: 1, recipe_id: 3)
comment4 = Comment.create(comment: "That tritip was amazing!", user_id: 2, recipe_id: 10)
comment5 = Comment.create(comment: "These street tacos are really easy to make and super delicious.", user_id: 2, recipe_id: 8)






