# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

melissa = User.create(name: "Melissa Funk", username: "melissafunk")
gabe = User.create(name: "Gabe Rodriguez", username: "gaberodgriguez")

carbonara = Recipe.create(title: "Carbonara", image: "https://assets.bonappetit.com/photos/5a6f48f94f860a026c60fd71/16:9/w_960,c_limit/pasta-carbonara.jpg", cuisine: "Italian", directions: "1. Heat 6 qt. water in a large pot over high. When water starts to steam, add 3 Tbsp. salt and cover pot with a lid (this will bring water to a boil faster; 2. While you are waiting on the water, do a little prep. Remove 4 oz. guanciale from packaging and cut into about 1x¼ strips. Finely grate 2 oz. cheese and set aside one-quarter of cheese for later; 3. Whisk 4 egg yolks and 2 whole eggs in a medium bowl until no streaks remain, then stir in remaining grated cheese. Add several cranks of pepper and set aside; 4. Working next to pot, heat 2 Tbsp. oil in a large Dutch oven or other heavy pot over medium. Add guanciale and cook, stirring occasionally, until crisp around the edges, 7–10 minutes; 5. Remove pot from heat. Using a wooden spoon, fish out guanciale and transfer to a small bowl. Pour fat into a heatproof measuring cup, then add back about 3 Tbsp. to pot. Discard any remaining fat; 6. Cook 1 lb. pasta in boiling water, stirring occasionally, 2 minutes shy of package instructions. Just before pasta is finished, scoop out 1¾ cups pasta cooking liquid with same heatproof measuring cup; 7. Add 1 cup reserved pasta cooking liquid to Dutch oven and bring to a boil over medium-high. Drain pasta in a colander, then transfer to Dutch oven; 8. Cook pasta, stirring constantly and vigorously, until al dente and water is reduced by about half, about 2 minutes. Remove pot from heat; 9.Whisk ¼ cup pasta cooking liquid into reserved egg mixture, then very slowly stream into Dutch oven, stirring constantly, until cheese is melted and egg is thickened to form a glossy sauce. Season with salt, if needed. Thin sauce with remaining ½ cup pasta cooking liquid, adding a tablespoonful at a time, until it's the consistency of heavy cream (you most likely won’t use all of it); 10. Mix in guanciale and divide pasta among bowls. Top with pepper and reserved cheese.", ingredients: "4 servings; 3 Tbsp. kosher salt plus more; 4 oz. pancetta; 2 oz. parmesan; 4 large egg yolks; 2 large eggs, 2 Tbsp. extra-virgin olive oil; 1 lb. spaghetti, bucatini, or rigatoni; freshly ground black pepper")



ribeye = Recipe.create(title: "Ribeye Steak", image: https://imagesvc.meredithcorp.io/v3/mm/image?url=https://static.onecms.io/wp-content/uploads/sites/9/2014/01/10/201402-xl-butter-basted-rib-eye-steak-2000.jpg, cuisine: "American", directions: "1. Season the rib eye steaks all over with salt and freshly ground pepper. Let the meat stand at room temperature for 30 minutes; 2. In a large cast-iron skillet, heat the canola oil until shimmering. Add the steaks and cook over high heat until crusty on the bottom, about 5 minutes. Turn the steaks and add the butter, thyme, garlic and rosemary to the skillet. Cook over high heat, basting the steaks with the melted butter, garlic and herbs, until the steaks are medium-rare, 5 to 7 minutes longer. Transfer the steaks to a cutting board and let rest for 10 minutes. Cut the steaks off the bone, then slice the meat across the grain and serve.", ingredients: " Two 1 1/4-pound, bone-in rib eye steaks; Kosher Salt; Freshly ground pepper; 2 tablespoons canola oil; 4 tablespoons unsalted butter; 4 thyme sprigs; 3 garlic cloves; 1 rosemary sprig")


tritip = Recipe.create(title "Tri-Tip with Chimichurri", image: https://assets.epicurious.com/photos/577d24a8fdf2b77e68400f4f/master/w_1280%2Cc_limit/tri-tip-with-chimichuri-BA-070616.jpg, cuisine: "American", directions: "1.Mix sesame seeds, paprika, 2 Tbsp. oil, 2 tsp. salt, and 2 tsp. pepper in a small bowl to combine. Rub all over steak and let sit at room temperature 30 minutes; 2.Meanwhile, prepare a grill for medium-high, indirect heat (for a charcoal grill, bank coals on one side of grill; for a gas grill, leave one or two burners off). Place steak over indirect heat, cover grill, and grill, turning once, until an instant-read thermometer inserted into the thickest part of steak registers 115°F, 20–30 minutes. Move steak to direct heat and grill until lightly charred, about 2 minutes per side, or until an instant-read thermometer registers 120°F for medium-rare (temperature will continue to rise off heat). Transfer to a cutting board and let rest 10 minutes before slicing against the grain; 3. While steak is resting, combine garlic, parsley, cilantro, vinegar, agave nectar, and remaining 1/2 cup oil; season with salt and pepper Serve steak with chimichurri", ingredients: "1 tablespoon sesame seeds; 1 tablespoon smoked paprika; 2 tablespoons plus 1/2 cup olive oil; 2 teaspoons kosher salt, plus more; 2 teaspoons freshly ground black pepper; 2 pounds tri-tip steak or two 1-pound sirloin steaks; 2 garlic cloves,finely grated; 2 cups finely chopped parsley; 1/2 cup finely chopped cilantro; 1/4 cup red wine vinegar; 1 tablespoon agave nectar")





